### ISSUE TITLE
Target Target Frame Issue

### ISSUE THREAD

**Issue by Cippopotamas** [Gendr/HideBlizzard#2]
I'm playing Classic wow and am receiving the following error:

Date: 2019-11-06 22:34:39
ID: 1
Error occured in: AddOn: HideBlizzard
Count: 1
Message: Note: AddOn HideBlizzard attempted to call a protected function (TargetFrameToT:Show()) during combat lockdown.
Debug:
   [C]: Show()
   ..\FrameXML\TargetFrame.lua:910: TargetofTarget_Update()
   ..\FrameXML\TargetFrame.lua:109: TargetFrame_Update()
   ..\FrameXML\TargetFrame.lua:150:
      ..\FrameXML\TargetFrame.lua:142
   [C]: CameraOrSelectOrMoveStop()
   [string "CAMERAORSELECTORMOVE"]:4:
      [string "CAMERAORSELECTORMOVE"]:1

**Comment by Gendr** [comment]
Were you trying to toggle "Target Unit Frame" option while in combat?

**Comment by Gendr** [comment]
It's complaining about a tainted function that it hasn't accessed yet. I believe this is a blizzard bug.
